#!/usr/bin/env node

const express = require('express');
const path = require('path');
const config = require('./config');

const app = express();

// Serve static files from the public directory
app.use(express.static(path.join(__dirname, config.staticDir)));

// Start the server
app.listen(config.port, () => {
    console.log(`Server is running at http://localhost:${config.port}`);
});
