#!/usr/bin/env node

const express = require('express');
const path    = require('path');
const config  = require('./config');

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, config.staticDir)));

app.listen(config.port, () => {
    console.log(`Frontend  -> http://localhost:${config.port}`);
});
